name: basic-checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos-checks:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run basic file checks
        run: bash ./scripts/check-files.sh
